import ExcelJS from "exceljs";

export type GoodsFormType = "GOODS_IN" | "GOODS_OUT";

export type GoodsFormItem = {
    name: string;
    quantity: number;
    handling_tags?: string[];
};

export type GoodsFormPayload = {
    form_type: GoodsFormType;
    order_id: string;
    company_name: string;
    brand_name?: string;
    venue_name?: string;
    venue_city?: string;
    event_start_date?: Date | string | null;
    event_end_date?: Date | string | null;
    trip_type?: string;
    vehicle_type?: string;
    contact_name?: string;
    contact_phone?: string;
    delivery_window?: { start?: Date | string | null; end?: Date | string | null } | null;
    pickup_window?: { start?: Date | string | null; end?: Date | string | null } | null;
    generated_by?: string;
    items: GoodsFormItem[];
};

const formatDateTime = (value?: Date | string | null) => {
    if (!value) return "";
    const d = new Date(value);
    if (Number.isNaN(d.getTime())) return "";
    return d.toISOString().slice(0, 16).replace("T", " ");
};

const formatWindow = (
    window?: { start?: Date | string | null; end?: Date | string | null } | null
) => {
    if (!window) return "";
    const start = formatDateTime(window.start);
    const end = formatDateTime(window.end);
    if (!start && !end) return "";
    return `${start}${end ? ` -> ${end}` : ""}`;
};

const addLabelValue = (sheet: ExcelJS.Worksheet, row: number, label: string, value: string) => {
    sheet.getCell(`A${row}`).value = label;
    sheet.getCell(`A${row}`).font = { bold: true };
    sheet.mergeCells(`B${row}:H${row}`);
    sheet.getCell(`B${row}`).value = value || "";
};

export const generateGoodsFormXlsx = async (payload: GoodsFormPayload): Promise<Buffer> => {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet(
        payload.form_type === "GOODS_IN" ? "GOODS IN" : "GOODS OUT"
    );

    sheet.columns = [
        { key: "a", width: 8 },
        { key: "b", width: 34 },
        { key: "c", width: 10 },
        { key: "d", width: 16 },
        { key: "e", width: 14 },
        { key: "f", width: 16 },
        { key: "g", width: 16 },
        { key: "h", width: 24 },
    ];

    const title = payload.form_type === "GOODS_IN" ? "GOODS IN FORM" : "GOODS OUT FORM";
    sheet.mergeCells("A1:H1");
    sheet.getCell("A1").value = title;
    sheet.getCell("A1").font = { bold: true, size: 16 };
    sheet.getCell("A1").alignment = { horizontal: "center" };

    addLabelValue(sheet, 3, "Order #", payload.order_id);
    addLabelValue(sheet, 4, "Company", payload.company_name);
    addLabelValue(sheet, 5, "Brand", payload.brand_name || "");
    addLabelValue(
        sheet,
        6,
        "Venue",
        [payload.venue_name, payload.venue_city].filter(Boolean).join(" - ")
    );
    addLabelValue(
        sheet,
        7,
        "Event Dates",
        `${formatDateTime(payload.event_start_date)} -> ${formatDateTime(payload.event_end_date)}`
    );
    addLabelValue(sheet, 8, "Trip Type", payload.trip_type || "");
    addLabelValue(sheet, 9, "Vehicle Type", payload.vehicle_type || "");
    addLabelValue(
        sheet,
        10,
        "Contact",
        [payload.contact_name, payload.contact_phone].filter(Boolean).join(" | ")
    );
    addLabelValue(sheet, 11, "Delivery Window", formatWindow(payload.delivery_window));
    addLabelValue(sheet, 12, "Pickup Window", formatWindow(payload.pickup_window));
    addLabelValue(sheet, 13, "Generated By", payload.generated_by || "");

    sheet.mergeCells("A15:H15");
    sheet.getCell("A15").value = "Item List";
    sheet.getCell("A15").font = { bold: true };

    const tableHeaderRow = 16;
    const headers = [
        "#",
        "Item / Asset",
        "Qty",
        "Handling Tags",
        "Condition",
        "Scanned Qty",
        "Remarks",
    ];
    headers.forEach((header, index) => {
        const cell = sheet.getCell(tableHeaderRow, index + 1);
        cell.value = header;
        cell.font = { bold: true };
        cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "FFEFEFEF" },
        };
    });

    const items = payload.items.length > 0 ? payload.items : [{ name: "", quantity: 0 }];
    items.forEach((item, index) => {
        const row = tableHeaderRow + 1 + index;
        sheet.getCell(`A${row}`).value = index + 1;
        sheet.getCell(`B${row}`).value = item.name;
        sheet.getCell(`C${row}`).value = item.quantity;
        sheet.getCell(`D${row}`).value = (item.handling_tags || []).join(", ");
    });

    const footerRow = tableHeaderRow + 3 + Math.max(items.length, 6);
    sheet.mergeCells(`A${footerRow}:H${footerRow}`);
    sheet.getCell(`A${footerRow}`).value =
        "Manual fields below are intentionally left blank for warehouse operations.";
    sheet.getCell(`A${footerRow}`).font = { italic: true, size: 10 };

    addLabelValue(sheet, footerRow + 2, "Prepared By", "");
    addLabelValue(sheet, footerRow + 3, "Checked By", "");
    addLabelValue(sheet, footerRow + 4, "Driver Signature", "");
    addLabelValue(sheet, footerRow + 5, "Receiver Signature", "");

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer as ArrayBuffer);
};
